### ISSUE TITLE
As a recipient of an `&rps` challenge, I want to be informed when an invite times out

### ISSUE THREAD

**Issue by dekarrin** [thewaifuproject/waifubot#1]
Expected behavior:
In RPS, if getting a move from a user takes too long, bot should indicate to the player that they have taken too long to pick a move 

Actual behavior:
In RPS, if getting a move from a user takes too long, bot appears to time out the session without indicating that this is the case.

Repro steps:
* Use `&rps` command to challenge someone to a game.
* Challengee does not give move within the timeout threshold.
* Challengee attempts to give move command, such as `Scissors`, in DM to bot.

**Comment by VGarK** [comment]
Alright! Thanks dek for reporting this. I'll look into it and get it implemented :muscle:

**Comment by VGarK** [comment]
Just fixed it. I'll be releasing the code tomorrow, hope you enjoy it!

**Comment by corollari** [comment]
Closing as it's been fixed.
